services:
    KeylightUtilBundle\Services\Asset\AssetManagerInterface: '@KeylightUtilBundle\Services\Asset\AssetManager'
    keylight_util_asset_manager: '@KeylightUtilBundle\Services\Asset\AssetManager'
    KeylightUtilBundle\Services\Asset\AssetManager: ~

    keylight_util_generic_asset_handler: '@KeylightUtilBundle\Services\Asset\Handlers\GenericAssetHandler'
    KeylightUtilBundle\Services\Asset\Handlers\GenericAssetHandler:
        arguments:
            - '@KeylightUtilBundle\Services\Asset\Storage\AssetStorage'
            - "@KeylightUtilBundle\Services\EntityManager\EntityManager"
        public: false
        tags:
            - { name: keylight.asset_handler, priority: 255 }

    keylight_util_image_asset_handler: '@KeylightUtilBundle\Services\Asset\Handlers\ImageAssetHandler'
    KeylightUtilBundle\Services\Asset\Handlers\ImageAssetHandler:
        arguments:
            - '@KeylightUtilBundle\Services\Asset\Storage\AssetStorage'
            - "@KeylightUtilBundle\Services\Asset\AssetFactory"
            - "%keylight_util_asset_images%"
        public: false
        tags:
            - { name: keylight.asset_handler, priority: 50 }

    keylight_util_pdf_asset_handler: '@KeylightUtilBundle\Services\Asset\Handlers\PdfAssetHandler'
    KeylightUtilBundle\Services\Asset\Handlers\PdfAssetHandler:
        arguments:
            - '@KeylightUtilBundle\Services\Asset\Storage\AssetStorage'
            - "@KeylightUtilBundle\Services\Asset\AssetFactory"
            - "%keylight_util_asset_pdf%"
        public: false
        tags:
            - { name: keylight.asset_handler, priority: 50 }

    keylight_util_asset_sanitizer: '@KeylightUtilBundle\Services\Asset\AssetSanitizer'
    KeylightUtilBundle\Services\Asset\AssetSanitizer:
        arguments:
            - "@KeylightUtilBundle\Entity\Repository\AssetRepository"
            - "@KeylightUtilBundle\Services\Asset\Providers\AssetProvider"
            - "@KeylightUtilBundle\Services\Asset\AssetManager"
            - "@KeylightUtilBundle\Services\EntityManager\EntityManager"
            - "%keylight_util_asset_images%"

    keylight_util_asset_repository: '@KeylightUtilBundle\Entity\Repository\AssetRepository'
    KeylightUtilBundle\Entity\Repository\AssetRepository:
        factory: doctrine.orm.entity_manager:getRepository
        arguments:
            - "KeylightUtilBundle:Asset"

    keylight_util_asset_factory: '@KeylightUtilBundle\Services\Asset\AssetFactory'
    KeylightUtilBundle\Services\Asset\AssetFactory: ~

    # PROVIDERS
    keylight_util_asset_provider: '@KeylightUtilBundle\Services\Asset\Providers\AssetProvider'
    KeylightUtilBundle\Services\Asset\Providers\AssetProviderInterface: '@KeylightUtilBundle\Services\Asset\Providers\AssetProvider'
    KeylightUtilBundle\Services\Asset\Providers\AssetProvider:
        arguments:
            - "@oneup_flysystem.default_filesystem"

    keylight_util_cloudfront_asset_provider: '@KeylightUtilBundle\Services\Asset\Providers\AWS\CloudfrontAssetProvider'
    KeylightUtilBundle\Services\Asset\Providers\AWS\CloudfrontAssetProvider:
        arguments:
            - "%keylight_util_cloudfront_public_endpoint%"
            - "%keylight_util_cloudfront_secure_endpoint%"
            - "@keylight_util_cloudfront_client"
            - "%keylight_util_cloudfront_private_key%"
            - "%keylight_util_cloudfront_private_key_pair_id%"
            - "%keylight_util_asset_public_base_path%"
            - "%keylight_util_asset_secure_base_path%"
        tags:
            - { name: keylight.asset_provider }

    keylight_util_local_asset_provider: '@KeylightUtilBundle\Services\Asset\Providers\Local\LocalAssetProvider'
    KeylightUtilBundle\Services\Asset\Providers\Local\LocalAssetProvider:
        arguments:
            - "@oneup_flysystem.default_filesystem"
        tags:
            - { name: keylight.asset_provider }

    KeylightUtilBundle\Services\Asset\Storage\AssetStorageInterface: '@KeylightUtilBundle\Services\Asset\Storage\AssetStorage'
    keylight_util_asset_storage: '@KeylightUtilBundle\Services\Asset\Storage\AssetStorage'
    KeylightUtilBundle\Services\Asset\Storage\AssetStorage:
        arguments:
            - "@oneup_flysystem.default_filesystem"
            - "%keylight_util_asset_public_base_path%"
            - "%keylight_util_asset_secure_base_path%"
            - "%keylight_util_asset_folder%"
