services:
    keylight_util_s3_client:
        class: Aws\S3\S3Client
        arguments:
            -
                version: '2006-03-01'
                region: "eu-central-1"
                credentials:
                    key: "%keylight_util_s3_access_key_id%"
                    secret: "%keylight_util_s3_secret_access_key%"
    keylight_util_cloudfront_client:
        class: Aws\CloudFront\CloudFrontClient
        arguments:
            -
                version: "2016-01-13"
                region: "eu-central-1"
                credentials:
                    key: "%keylight_util_s3_access_key_id%"
                    secret: "%keylight_util_s3_secret_access_key%"
