services:
    keylight_entity_manager:
        class: KeylightUtilBundle\Services\EntityManager\EntityManager
        arguments:
            - @doctrine.orm.entity_manager
    keylight_twig_extension:
        class: KeylightUtilBundle\Services\Twig\KeylightTwigExtension
        arguments:
            - @keylight_string_formatter
        public: false
        tags:
            - { name: twig.extension }
    keylight_string_formatter:
        class: KeylightUtilBundle\Services\String\StringFormatter
    keylight_mailer:
        class: KeylightUtilBundle\Services\Mailer\MailerService
        arguments:
            - @mailer
            - %keylight_util_sender_address%

