services:
    keylight_util_entity_manager:
        class: KeylightUtilBundle\Services\EntityManager\EntityManager
        arguments:
            - "@doctrine.orm.entity_manager"
    keylight_util_twig_extension:
        class: KeylightUtilBundle\Services\Twig\KeylightTwigExtension
        arguments:
            - "@keylight_util_string_formatter"
            - "@keylight_util_asset_provider"
            - "@translator"
        public: false
        tags:
            - { name: twig.extension }
    keylight_util_string_formatter:
        class: KeylightUtilBundle\Services\String\StringFormatter
        arguments:
            - "%locale%"
    keylight_util_mailer:
        class: KeylightUtilBundle\Services\Mailer\MailerService
        arguments:
            - "@mailer"
            - "%keylight_util_sender_address%"
    keylight_util_random_string_util:
        class: KeylightUtilBundle\Services\String\RandomStringUtil
    keylight_util_uuid_provider:
        class: KeylightUtilBundle\Services\Uuid\UuidProvider
        arguments:
            - "@keylight_util_entity_manager"
            - "@keylight_util_random_string_util"
