services:
    keylight_util_entity_manager: '@KeylightUtilBundle\Services\EntityManager\EntityManager'
    KeylightUtilBundle\Services\EntityManager\EntityManager:
        arguments:
            - "@doctrine.orm.entity_manager"

    keylight_util_twig_extension: '@KeylightUtilBundle\Services\Twig\KeylightTwigExtension'
    KeylightUtilBundle\Services\Twig\KeylightTwigExtension:
        arguments:
            - "@KeylightUtilBundle\Services\String\StringFormatter"
            - "@KeylightUtilBundle\Services\Asset\Providers\AssetProvider"
            - "@translator"
        public: false
        tags:
            - { name: twig.extension }

    keylight_util_string_formatter: '@KeylightUtilBundle\Services\String\StringFormatter'
    KeylightUtilBundle\Services\String\StringFormatter:
        arguments:
            - "%locale%"

    keylight_util_mailer: '@KeylightUtilBundle\Services\Mailer\MailerService'
    KeylightUtilBundle\Services\Mailer\MailerService:
        arguments:
            - "@mailer"
            - "%keylight_util_sender_address%"
            - "%keylight_util_sender_name%"

    keylight_util_random_string_util: '@KeylightUtilBundle\Services\String\RandomStringUtil'
    KeylightUtilBundle\Services\String\RandomStringUtil: ~

    keylight_util_uuid_provider: '@KeylightUtilBundle\Services\Uuid\UuidProvider'
    KeylightUtilBundle\Services\Uuid\UuidProvider:
        arguments:
            - "@KeylightUtilBundle\Services\EntityManager\EntityManager"
            - "@KeylightUtilBundle\Services\String\RandomStringUtil"

    keylight_response_provider: '@KeylightUtilBundle\Services\Response\ResponseProvider'
    KeylightUtilBundle\Services\Response\ResponseProvider: ~

    keylight_util_health_check_provider: '@KeylightUtilBundle\Services\Health\HealthCheckProvider'
    KeylightUtilBundle\Services\Health\HealthCheckProvider: ~

    keylight_util_health_check_git: '@KeylightUtilBundle\Services\Health\GitHealthCheckProvider'
    KeylightUtilBundle\Services\Health\GitHealthCheckProvider:
        public: false
        tags:
            - { name: keylight_util.health_check }
