services:
    keylight_util_entity_manager:
        class: KeylightUtilBundle\Services\EntityManager\EntityManager
        arguments:
            - "@doctrine.orm.entity_manager"
    keylight_util_twig_extension:
        class: KeylightUtilBundle\Services\Twig\KeylightTwigExtension
        arguments:
            - "@keylight_util_string_formatter"
            - "@keylight_util_asset_provider"
            - "@translator"
        public: false
        tags:
            - { name: twig.extension }
    keylight_util_string_formatter:
        class: KeylightUtilBundle\Services\String\StringFormatter
        arguments:
            - "%locale%"
    keylight_util_mailer:
        class: KeylightUtilBundle\Services\Mailer\MailerService
        arguments:
            - "@mailer"
            - "%keylight_util_sender_address%"
            - "%keylight_util_sender_name%"
    keylight_util_random_string_util:
        class: KeylightUtilBundle\Services\String\RandomStringUtil
    keylight_util_uuid_provider:
        class: KeylightUtilBundle\Services\Uuid\UuidProvider
        arguments:
            - "@keylight_util_entity_manager"
            - "@keylight_util_random_string_util"
    keylight_response_provider:
        class: KeylightUtilBundle\Services\Response\ResponseProvider
    keylight_util_health_check_provider:
        class: KeylightUtilBundle\Services\Health\HealthCheckProvider
    keylight_util_health_check_git:
        class: KeylightUtilBundle\Services\Health\GitHealthCheckProvider
        public: false
        tags:
            - { name: keylight_util.health_check }
    keylight_util_health_check_db:
        class: KeylightUtilBundle\Services\Health\DBHealthCheckProvider
        public: false
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: keylight_util.health_check }

    KeylightUtilBundle\Services\Depersonalize\Depersonalize:
        class: KeylightUtilBundle\Services\Depersonalize\Depersonalize
        arguments:
            - '@KeylightUtilBundle\Services\Depersonalize\EntityHelperContainer'

    KeylightUtilBundle\Services\Depersonalize\EntityHelperContainer:
        class: KeylightUtilBundle\Services\Depersonalize\EntityHelperContainer

    KeylightUtilBundle\Services\Log\Processor\AppNameProcessor:
        class: KeylightUtilBundle\Services\Log\Processor\AppNameProcessor
        arguments:
            - '@Symfony\Component\HttpFoundation\RequestStack'
        tags: [ monolog.processor ]

    KeylightUtilBundle\Services\Log\Processor\DoctrineContextProcessor:
        class: KeylightUtilBundle\Services\Log\Processor\DoctrineContextProcessor
        arguments:
            - '@Symfony\Component\HttpFoundation\RequestStack'
        tags: [ monolog.processor ]

    KeylightUtilBundle\Services\Log\Processor\RequestIdProcessor:
        class: KeylightUtilBundle\Services\Log\Processor\RequestIdProcessor
        arguments:
            - '@Symfony\Component\HttpFoundation\RequestStack'
        tags: [ monolog.processor ]

    KeylightUtilBundle\Services\Log\Processor\SessionIdProcessor:
        class: KeylightUtilBundle\Services\Log\Processor\SessionIdProcessor
        arguments:
            - '@Symfony\Component\HttpFoundation\Session\SessionInterface'
        tags: [ monolog.processor ]
